name: Tally Elections Tool
run-name: Test Tally Elections Tool
on:
  pull_request:
    paths:
    - 'elections/tools/**'
jobs:
  tally_test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The name of the branch is ${{ github.ref }} and the repository is ${{ github.repository }}."
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Run unit tests and fuzzer
        run: cd ${{ github.workspace }} && make fuzztimed
